const fs = require('fs');
let c = fs.readFileSync('src/features/portals/trainer/Assignment.tsx', 'utf8');
const lines = c.split('\n');

// Remove lines 363-390 (index 362-389)
lines.splice(362, 28);

// Insert the advanced quiz section
const newSection = [
  "      {/* Quiz list */}",
  "      {quizzes.length > 0 && (",
  "        <div className='card' style={{ marginTop: 16, padding: '18px 16px' }}>",
  "          <div className='card-title' style={{ marginBottom: 12 }}>{de ? 'Quizzes' : 'Quizzes'} ({quizzes.length})</div>",
  "          {quizzes.map((q) => {",
  "            const attempts = (quizAttempts && quizAttempts[q.id]) || [];",
  "            const byPart = {};",
  "            attempts.forEach((a) => { if (!byPart[a.participantId]) byPart[a.participantId] = []; byPart[a.participantId].push(a); });",
  "            const partIds = Object.keys(byPart);",
  "            const passed = partIds.filter(pid => byPart[pid].some((a) => a.passed)).length;",
  "            const failed = partIds.filter(pid => byPart[pid].every((a) => !a.passed)).length;",
  "            const isExp = expandedQuiz === q.id;",
  "            return (",
  "              <div key={q.id} style={{ borderRadius: 9, background: '#F8FAFF', marginBottom: 8, border: '1px solid #E8EEFF', overflow: 'hidden' }}>",
  "                <div style={{ padding: '10px 14px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', cursor: 'pointer' }}",
  "                  onClick={async () => {",
  "                    if (isExp) { setExpandedQuiz(null); return; }",
  "                    setExpandedQuiz(q.id);",
  "                    if (!quizAttempts[q.id]) {",
  "                      const att = await api('/quiz/' + q.id + '/attempts').catch(() => []);",
  "                      setQuizAttempts((prev) => ({ ...prev, [q.id]: Array.isArray(att) ? att : [] }));",
  "                    }",
  "                  }}>",
  "                  <div>",
  "                    <div style={{ fontWeight: 600, fontSize: 13 }}>{q.title}</div>",
  "                    <div style={{ fontSize: 11, color: '#64748B', marginTop: 2, display: 'flex', gap: 10 }}>",
  "                      <span>{q.questions?.length ?? 0} {de ? 'Fragen' : 'Q'}</span>",
  "                      {partIds.length > 0 && (<><span style={{ color: '#0FB6A0' }}>+{passed} {de ? 'bestanden' : 'passed'}</span><span style={{ color: '#F4475F' }}>-{failed} {de ? 'n. bestanden' : 'failed'}</span></>)}",
  "                    </div>",
  "                  </div>",
  "                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>",
  "                    <select defaultValue='' onClick={(e) => e.stopPropagation()} onChange={async (e) => {",
  "                      const pid = e.target.value; if (!pid) return; e.target.value = '';",
  "                      try {",
  "                        await fetch('/api/v1/quiz/' + q.id + '/attempts/' + pid, { method: 'DELETE', headers: { Authorization: 'Bearer ' + localStorage.getItem('token') } });",
  "                        setQuizAttempts((prev) => ({ ...prev, [q.id]: (prev[q.id] || []).filter((a) => a.participantId !== pid) }));",
  "                        alert(de ? 'Quiz zurueckgesetzt!' : 'Quiz reset!');",
  "                      } catch { alert('Error'); }",
  "                    }} style={{ fontSize: 11, padding: '4px 8px', borderRadius: 7, border: '1px solid #F59E0B55', color: '#F59E0B', cursor: 'pointer', outline: 'none', background: '#FFFBEB' }}>",
  "                      <option value=''>{de ? 'Zuruecksetzen...' : 'Reset for...'}</option>",
  "                      {parts.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}",
  "                    </select>",
  "                    <span style={{ fontSize: 12, color: '#94A3B8' }}>{isExp ? '-' : '+'}</span>",
  "                  </div>",
  "                </div>",
  "                {isExp && (",
  "                  <div style={{ borderTop: '1px solid #E8EEFF', padding: '10px 14px' }}>",
  "                    {partIds.length === 0 ? (",
  "                      <div style={{ fontSize: 12, color: '#94A3B8', textAlign: 'center' }}>{de ? 'Noch keine Versuche' : 'No attempts yet'}</div>",
  "                    ) : (",
  "                      <table style={{ width: '100%', fontSize: 12, borderCollapse: 'collapse' }}>",
  "                        <thead><tr style={{ color: '#64748B', fontSize: 11 }}>",
  "                          <th style={{ textAlign: 'left', paddingBottom: 6 }}>{de ? 'Teilnehmer' : 'Participant'}</th>",
  "                          <th style={{ textAlign: 'center', paddingBottom: 6 }}>{de ? 'Versuche' : 'Attempts'}</th>",
  "                          <th style={{ textAlign: 'center', paddingBottom: 6 }}>{de ? 'Bestes Ergebnis' : 'Best Score'}</th>",
  "                          <th style={{ textAlign: 'center', paddingBottom: 6 }}>Status</th>",
  "                        </tr></thead>",
  "                        <tbody>",
  "                          {partIds.map(pid => {",
  "                            const pa = byPart[pid];",
  "                            const best = pa.reduce((b, a) => (a.score > b.score ? a : b), pa[0]);",
  "                            const pct = best.total > 0 ? Math.round((best.score / best.total) * 100) : 0;",
  "                            const pName = parts.find((p) => p.id === pid)?.name || pid.slice(0,8);",
  "                            return (",
  "                              <tr key={pid} style={{ borderTop: '1px solid #F1F5F9' }}>",
  "                                <td style={{ padding: '6px 0', fontWeight: 500 }}>{pName}</td>",
  "                                <td style={{ textAlign: 'center', color: '#64748B' }}>{pa.length}</td>",
  "                                <td style={{ textAlign: 'center', fontWeight: 700, color: best.passed ? '#0FB6A0' : '#F4475F' }}>{best.score}/{best.total} ({pct}%)</td>",
  "                                <td style={{ textAlign: 'center' }}><span style={{ fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 20, background: best.passed ? '#0FB6A020' : '#F4475F15', color: best.passed ? '#0FB6A0' : '#F4475F' }}>{best.passed ? (de ? 'Bestanden' : 'Passed') : (de ? 'Nicht bestanden' : 'Failed')}</span></td>",
  "                              </tr>",
  "                            );",
  "                          })}",
  "                        </tbody>",
  "                      </table>",
  "                    )}",
  "                  </div>",
  "                )}",
  "              </div>",
  "            );",
  "          })}",
  "        </div>",
  "      )}"
];

lines.splice(362, 0, ...newSection);
fs.writeFileSync('src/features/portals/trainer/Assignment.tsx', lines.join('\n'), 'utf8');
console.log('DONE - total lines:', lines.length);
